### ISSUE TITLE
Books don't count towards Bookworm

### ISSUE THREAD

**Issue by RiccardoP** [ApexPredator13/Nldb3#5]
A few books don't get counted for Bookworm transformation (e.g. Bible and Satanic Bible)

**Comment by ApexPredator13** [comment]
Thanks for pointing that out. I checked the database and a few books were indeed missing:

- Monster Manual
- Satanic Bible
- The Bible
- The Necronomicon
- Book of the Dead

I added them now.

It shouldn't be too hard to identify and auto-fix the submitted episodes that were affected by this.
Will be on my todo list!

**Comment by ApexPredator13** [comment]
It's been a while but I finally resolved the transformation issue once and for all by adding a 'recompile' feature to the backend. It was WAY more work than I expected at first with lots of potential to break things, that's why it took so long.

Nevertheless, it is now possible to
- test episodes for errors whenever the rules change
- rewrite them with a single mouse click
